C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=33
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=32
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=24
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=18
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=17
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=14
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=13
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=12
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=11
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=10
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=9
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=8
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=7
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=6
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=5
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=4
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=3
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=2
C:\Anaconda\python.exe makevideo.py --section=SPORTS --upload --backdate=1